---
- name: aio-ansible - Template SO
  hosts: "{{ ansibleHost }}"
  tasks:
     - name: TASK "{{ output }}" 
       command: "{{ ansibleCommand }}"
       register: job_output
     - name: Set fact
       set_fact: '{{ output }}={{ job_output }}'
